server:
  port: 8080
  error:
    path: /error

spring:
#  servlet:
#    multipart:
#      max-file-size:

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:6523/f10?createDatabaseIfNotExist=true #change to postgres/localhost
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: false
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'

    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp